https://github.com/keras-team/keras-io/blob/master/examples/structured_data/collaborative_filtering_movielens.py

pimpwhippa@pimpwhippa-Aspire-E5-473G:~/Works/recommender/flask$ 
docker cp ../model_keras.py flask_flask_app_1:code/

root@48ad086244a7:/code# 
pip install pandas
pip install tensorflow #only compatible upto python 3.8

add all these for pip install in requirements.txt and rebuild using
docker-compose up --build

numpy needed to downgrade to <1.19.0 now is at 1.18.5
include 2 ports (flask and jupyter) in flask container but 
jupyter doesn't work yet

DannyIbo uses NMF model from scikit-learn and flask
Siddartha uses keras but no flask


docker build --tag python-flask:DannyIbo .

pimpwhippa@pimpwhippa-Aspire-E5-473G:~/Works/recommender/flask/DannyIbo$ 
docker run --name ibobox -d -it -v ~/data-test:/box python-flask:DannyIbo

docker run -d -p 5002:5003 --name=ibobox -v $PWD:/app python-flask:DannyIbo

สั่ง run ใหม่ แต่ไม่ได้ build ใหม่ ทำไมยังมี volume ติดมาให้ได้??
เป็นครั้งแรกในชีวิตโปรแกรมเมอร์ที่รู้ว่าเคาะเอ็นเต้อคราวนี้ไปแล้วรู้ว่าผลมันจะได้ออกมาเป็นยังไง

docker exec -it ibobox bash

export FLASK_RUN_PORT=5002
rm and run again, now doesn't work, address already in use
    app.run(debug=True,host='0.0.0.0', port=5002)
OSError: [Errno 98] Address already in use

so have to stop docker engine
container ID from docker inspect ibobox
3c2cdd7efd5dcbce9185eeb0c13d26435f46bc6947682cd2b365fe7aa7a814bb

you can change the port mapping by directly editing the hostconfig.json file 
at /var/lib/docker/containers/[hash_of_the_container]/hostconfig.json

/var/lib/docker/containers/3c2cdd7efd5dcbce9185eeb0c13d26435f46bc6947682cd2b365fe7aa7a814bb/hostconfig.json
no permission to getinto docker ;P

netstat -tulpn
to see which services are using ports

sudo lsof -i :5002

 COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 4646 root    4u  IPv6  65066      0t0  TCP *:rfe (LISTEN)

sudo kill -9 4646

 docker run --name=ibobox -p 5002:5000 python-flask:DannyIbo
 
 * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 122-175-908

 คราวนี้ได้ the connection was reset
 ก่อนหน้านี้ได้ unable to connect

 docker run --name=ibobox -p 5000:5002 python-flask:DannyIbo
 * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)

แต่ไปที่ 0.0.0.0:5000 เข้าได้ว่ะ?? งงที่สุด แต่ติด jinja หาไฟล์ templates ไม่เจอ

รันใหม่ ไม่ได้อีกแล้ว
 ps -fA | grep python

ไม่ได้ใส่ port=5002 ก็รันที่ 5000
 root@b3a1bd859c0a:/box# python app.py
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 พอไปที่ 5000 ได้ internal server error

docker run --name=ibobox -p 5000:5002 -v ${PWD}:/box python-flask:DannyIbo
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

docker run -it -v /home/dbfolder/:/db imagename
docker run --name=ibobox2 -p 5001:5003 -v ${PWD}:/box python-flask:DannyIbo

docker run -it --name=ibobox2 -v ${PWD}:/box python-flask:DannyIbo


ลองวิธีใหม่ที่จะใช้ jupyter จากในคอนเทนเนอร์ที่มี flask
ไปเอา docker image jupyter/tensorflow-notebook มา
แล้วใน dockerfile ใส่ใน requirements.txt ว่า Flask

docker build -t jupyter/tensorflow-notebook .

pimpwhippa@pimpwhippa-Aspire-E5-473G:~$ 
docker run --name=flask_jupyter -p 8888:8888 flask_jupyter:latest

บางทีก็ติดพาสเวิร์ด token บางทีก็ unable to connect, connection was reset
http://127.0.0.1:8888/tree

http://f883b5e8bee9:8888/?token=9a7e1f42e944ab95e0335b43bd93d925d3211d97ebf162dc

http://127.0.0.1:8888/?token=9a7e1f42e944ab95e0335b43bd93d925d3211d97ebf162dc
[I 20:10:22.034 NotebookApp] 302 GET /?token=9a7e1f42e944ab95e0335b43bd93d925d3211d97ebf162dc (172.17.0.1) 2.07ms
[I 20:10:31.942 NotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret

อย่างงี้เข้าได้
docker start flask_jupyter
docker exec -it flask_jupyter jupyter notebook list

หรือจะเข้าด้วย bash แล้วค่อยไป
docker exec -it flask_jupyter bash
่ีjupyter notebook list 
ก็ได้

http://0.0.0.0:8888/tree


docker run --name=flask_jupyter -p 8888:8888 -v ${PWD}:/flask_jupyter flask_jupyter:latest
โอ๊ย ทำได้แล้วน้ำตาจะไหล
คือแค่ setup jupyter notebook ใน docker ทำไมมันวุ่นวายอย่างงี้วะ นี่ขนาดแค่ใช้ในเครื่องตัวเองนะ

คือถ้าไปเปิดที่อื่นต้องดูเรื่อง container host port อีก แต่นี่คือเปิดด้วย http://127.0.0.1:8888/tree
แล้วประเด็นคือ ต้องใส่ -v mount ตอนรันเพื่อที่จะเซฟได้
ไม่งั้นทำๆไป เซฟไม่ได้ มันขึ้นเป็น read-only untrusted file
แต่พอ mnt แล้วเลยมีที่ให้เซฟ ข้อมูลจะได้ persist อยู่ที่ host แต่ที่คอนเทนเนอร์เองก็ไม่มีอยู่ดีนะ


กว่าจะเซ็ทอัพเสร็จ ส่วนdevelopment ของ deep learning เป็นหนึ่งใน fullstack ภาพรวม
คือต่อดาต้าเข้ากับส่วนเดฟแล้วก็ทำการเทรน จากนั้นก็เอาไปดีพลอย 
มีสามส่วน คือดาต้า เดฟกับเทรน และดีพลอย คือโปรดักชั่นใช้จริง
คือเทคโนโลยีที่ใช้ได้แก่
tensorflow, keras อยู่ในด็อกเก้ออิมเมจ
jupyter notebook ก็อยู่ในด็อกเก้ออิมเมจ
flask ใส่เพิ่มไปใน requirements.txt ตอนเขียน dockerfile
docker
sqlite install อยู่ที่ host เลย
pimpwhippa@pimpwhippa-Aspire-E5-473G:~$ 
sudo apt install sqlite3


ที่ต้องลงเพิ่ม
pip install googleapiclient
pip install fuzzywuzzy
pip install google-api-python-client
pip install flask_sqlalchemy
pip install pandas
pip install google-auth-oauthlib

Flask == 0.12
fuzzywuzzy
google-api-python-client
flask_sqlalchemy
pandas
numpy
google-auth-oauthlib
pysqlite3
tensorflow

301120

sqlite3 บ่นว่าไม่มี table ชื่อ ratings
ก็ยังไม่ได้ create table จริงๆ
ให้สร้างตารางด้วยไฟล์เหล่านี้ โดยให้แต่ละตารางมีชื่อตามแต่ละไฟล์

                table=os.path.splitext(os.path.basename(filename))[0]

                sql = 'drop table if exists "{}"'.format(table)
                db.execute(sql)

                sql = 'create table "{table}" ( {cols} )'.format(
                    table=table,
                    cols=','.join('"{}"'.format(col) for col in cols))
                db.execute(sql)


SELECT "userId", ratings."movieId", movies.title, rating FROM ratings JOIN movies ON ratings."movieId" = movies."movieId";

ก็เลยต้อง create table ก่อน?
เข้าไปในกล่อง สั่ง sqlite3
sqlite> .open recommender2.db
sqlite> .tables
links    movies   ratings  tags   
sqlite> 

มาต่อ flask ด้วยเลยงง
จะเรียก sqlite จากใน docker container จะเรียกยังไงนะ สั่ง sqlite3 แล้วบอกว่า command not found

docker run --name sqlitedanny -it -v /Works/recommender/flask/DannyIbo/:/box python-flask:DannyIbo

ตอนแรกบ่นว่าหาไฟล์ไม่เจอ
python: can't open file '/box/app.py': [Errno 2] No such file or directory
เลยสั่ง mount ใหม่ แล้วสั่ง -it

docker run -it --name=ibobox2 -v ${PWD}:/box python-flask:DannyIbo

เลิกบ่น และปริ๊น all_ratings ออกมาได้ แต่พอไปเรียกจาก browser ก็ยังขึ้นว่า internal server error อยู่ดี
แต่พอกลับมาดูในเทอร์มินัล ในคอนเทนเนอร์ คราวนี้ไม่มี GET error แล้ว คือจะมาบอกว่า
all_ratings is not defined ไม่ได้แล้วเพราะว่าสั่งปริ๊นมาได้แล้ว

อ้าวงงล่ะสิคราวนี้ flask ยังโชว์ให้ไม่ได้
แต่ py ไม่มีปัญหาอะไรแล้ว

ทำที่ ibobox แต่ไม่เห็นอะไรเลย เลยไปเปิดกล่อง jupyter tensorflow เพื่อไล่ดูว่าโค้ดบรรทัดไหนทำอะไร

ตอนแรกที่มาเริ่ม ibobox3 เพื่อจะต่อ pysqlite3

docker run -it --name=ibobox3 -v ${PWD}:/box python-flask:DannyIbo
ทำมาจนรันได้ถึง user_input
คราวนี้บ่นว่า ต้องมี active http request ถึงจะรันต่อได้

เลยต้องมารันใหม่แบบต่อพอร์ท
docker run --name=ibobox3 -p 5001:5003 -v ${PWD}:/box python-flask:DannyIbo

docker rm ibobox
rm recommender3.db
แล้วสั่งรันใหม่
docker run --name=ibobox3 -p 5001:5003 -v ${PWD}:/box python-flask:DannyIbo


ลง tensorflow เพิ่มในกล่อง ibobox3 ไม่ได้ ไม่รู้ทำไม
แม่งบอกว่า ไม่มีเวอร์ชั่นนี้

ส่วนลอง 
docker run --name=flask_tensorflow2 -p 5001:5003 -v ${PWD}:/flask_jupyter python-flask:DannyIbo

ก็รันได้ แต่ว่าพอไปเบราเซอร์แล้ว เปิดไม่ออกสักอัน?
/usr/local/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
 * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)

เลยงง ตอนนี้มาลองบิ้วใหม่โดยใช้ tensorflow เป็น base image
docker build -t tensorflow-flask:cmd .

docker run --name=tensorflow-flask5 -p 5002:5002 -v ${PWD}:/box tensorflow-flask:cmd

แต่ยังให้แสดงผลเป็น dataframe ไม่ได้ render template เนี่ย

ต่อพอร์ทไหม
จะรันดูเพื่อจะรู้ว่าในกล่องมี tensorflow ไหม ก็ต้องสั่ง python app.py
ซึ่งก็ต้องสั่งรันนั่นเอง

change from port=5002 to port=port trying to solve unable to connect port within 60 seconds
check if it works locally and in how long
docker run --name=flask-tf-port -p 5000:5000 -v ${PWD}:/box flask-tf:latest
